package com.allocator.contentservice.model;

public enum InAppNotificationType {
    COMMENT_ADDED,
    REPLY_ADDED,
    COMMENT_RESOLVED,
    COMMENT_REOPENED,
    ANNOTATION_CREATED,
    ANNOTATION_RESOLVED,
    REVIEW_REQUESTED,
    REVIEW_COMPLETED,
    REVIEW_APPROVED,
    REVIEW_APPROVED_WITH_CHANGES,
    REVIEW_CHANGES_REQUESTED,
    REVIEW_REJECTED,
    REVIEW_ESCALATED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    TASK_OVERDUE,
    EDIT_LOCK_CONFLICT
}
