package com.allocator.contentservice.model;

public enum ReferenceSourceType {
    WEBPAGE, JOURNAL_ARTICLE, BOOK, BOOK_CHAPTER, REPORT,
    ONLINE_VIDEO, NEWSPAPER_ARTICLE, BLOG_POST, ARTWORK,
    COMMENT, CONFERENCE_PAPER, CONFERENCE_SESSION, DATASET,
    DISSERTATION, ENCYCLOPEDIA, GOVERNMENT_DOCUMENT, INTERVIEW,
    MAGAZINE, PATENT, PODCAST, PRESS_RELEASE, SOFTWARE, SPEECH
}
