package com.allocator.contentservice.model;

public enum ResourceType {
    JOURNAL_ARTICLE,
    RESEARCH_PAPER,
    BOOK,
    BOOK_CHAPTER,
    NEWS_ARTICLE,
    MAGAZINE_ARTICLE,
    BLOG_POST,
    GOVERNMENT_PUBLICATION,
    REPORT,
    DATASET,
    THESIS,
    DISSERTATION,
    CONFERENCE_PAPER,
    WEBPAGE,
    YOUTUBE_VIDEO,
    VIMEO_VIDEO,
    PODCAST_EPISODE,
    PODCAST_SERIES,
    SOCIAL_MEDIA_POST,
    INTERVIEW,
    PRESS_RELEASE,
    FINANCIAL_RESEARCH,
    GENERIC_DOCUMENT
}
